version: '3.4'

services:
  vpn:
    container_name: anyconnect_vpn
    build:
      context: .
      dockerfile: vpn.Dockerfile
    environment:
      - ANYCONNECT_SERVER=${ANYCONNECT_SERVER}
      - ANYCONNECT_USER=${ANYCONNECT_USER}
      - ANYCONNECT_GROUP=${ANYCONNECT_GROUP}
      - ANYCONNECT_PASSWORD=${ANYCONNECT_PASSWORD}
      - ANYCONNECT_CERT=${ANYCONNECT_CERT}
    networks:
      - default
    privileged: true
    cap_add:
      - NET_ADMIN
    restart: "no"  # unless-stopped
    security_opt:
      - label=disable
    ports:
      - "1080:1080"
      - "1081:8888"
  proxy:
    container_name: anyconnect_proxy
    build:
      context: .
      dockerfile: proxy.Dockerfile
    healthcheck:
      test: ["CMD", "/sbin/ifconfig", "tun0"]
      interval: 10s
      timeout: 10s
      start_period: 10s
    labels:
      - autoheal=true
    restart: on-failure
    depends_on:
      - vpn
    network_mode: "service:vpn"
  http_proxy:
    container_name: anyconnect_http_proxy
    image: dannydirect/tinyproxy
    command: ["127.0.0.1", "192.168.0.0/16", "172.16.0.0/12"]
    labels:
      - autoheal=true
    restart: on-failure
    depends_on:
      - vpn
    network_mode: "service:vpn"
